-- Code generated by eluna-annotations-generator, PLEASE DO NOT EDIT

---@class Vehicle
local Vehicle = {}

---
--- Returns true if the [Unit] passenger is on board
---
---@param passenger Unit
---@return bool @ isOnBoard
function Vehicle:IsOnBoard(passenger) end

---
--- Returns the [Vehicle]'s owner
---
---@return Unit @ owner
function Vehicle:GetOwner() end

---
--- Returns the [Vehicle]'s entry
---
---@return uint32 @ entry
function Vehicle:GetEntry() end

---
--- Returns the [Vehicle]'s passenger in the specified seat
---
---@param seat int8
---@return Unit @ passenger
function Vehicle:GetPassenger(seat) end

---
--- Adds [Unit] passenger to a specified seat in the [Vehicle]
---
---@param passenger Unit
---@param seat int8
function Vehicle:AddPassenger(passenger, seat) end

---
--- Removes [Unit] passenger from the [Vehicle]
---
---@param passenger Unit
function Vehicle:RemovePassenger(passenger) end

return Vehicle

