-- Code generated by eluna-annotations-generator, PLEASE DO NOT EDIT

---@class WorldPacket
local WorldPacket = {}

---
--- Returns the opcode of the [WorldPacket].
---
---@return uint16 @ opcode
function WorldPacket:GetOpcode() end

---
--- Returns the size of the [WorldPacket].
---
---@return uint32 @ size
function WorldPacket:GetSize() end

---
--- Sets the opcode of the [WorldPacket] to the specified opcode.
---
---@param opcode Opcodes @ : see Opcodes.h for all known opcodes
function WorldPacket:SetOpcode(opcode) end

---
--- Reads and returns a signed 8-bit integer value from the [WorldPacket].
---
---@return int8 @ value
function WorldPacket:ReadByte() end

---
--- Reads and returns an unsigned 8-bit integer value from the [WorldPacket].
---
---@return uint8 @ value
function WorldPacket:ReadUByte() end

---
--- Reads and returns a signed 16-bit integer value from the [WorldPacket].
---
---@return int16 @ value
function WorldPacket:ReadShort() end

---
--- Reads and returns an unsigned 16-bit integer value from the [WorldPacket].
---
---@return uint16 @ value
function WorldPacket:ReadUShort() end

---
--- Reads and returns a signed 32-bit integer value from the [WorldPacket].
---
---@return int32 @ value
function WorldPacket:ReadLong() end

---
--- Reads and returns an unsigned 32-bit integer value from the [WorldPacket].
---
---@return uint32 @ value
function WorldPacket:ReadULong() end

---
--- Reads and returns a single-precision floating-point value from the [WorldPacket].
---
---@return float @ value
function WorldPacket:ReadFloat() end

---
--- Reads and returns a double-precision floating-point value from the [WorldPacket].
---
---@return double @ value
function WorldPacket:ReadDouble() end

---
--- Reads and returns an unsigned 64-bit integer value from the [WorldPacket].
---
---@return ObjectGuid @ value, : value returned as string
function WorldPacket:ReadGUID() end

---
--- Reads and returns a string value from the [WorldPacket].
---
---@return string @ value
function WorldPacket:ReadString() end

---
--- Writes an unsigned 64-bit integer value to the [WorldPacket].
---
---@param value ObjectGuid @ : the value to be written to the [WorldPacket]
function WorldPacket:WriteGUID(value) end

---
--- Writes a string to the [WorldPacket].
---
---@param value string @ : the string to be written to the [WorldPacket]
function WorldPacket:WriteString(value) end

---
--- Writes a signed 8-bit integer value to the [WorldPacket].
---
---@param value int8 @ : the int8 value to be written to the [WorldPacket]
function WorldPacket:WriteByte(value) end

---
--- Writes an unsigned 8-bit integer value to the [WorldPacket].
---
---@param value uint8 @ : the uint8 value to be written to the [WorldPacket]
function WorldPacket:WriteUByte(value) end

---
--- Writes a signed 16-bit integer value to the [WorldPacket].
---
---@param value int16 @ : the int16 value to be written to the [WorldPacket]
function WorldPacket:WriteShort(value) end

---
--- Writes an unsigned 16-bit integer value to the [WorldPacket].
---
---@param value uint16 @ : the uint16 value to be written to the [WorldPacket]
function WorldPacket:WriteUShort(value) end

---
--- Writes a signed 32-bit integer value to the [WorldPacket].
---
---@param value int32 @ : the int32 value to be written to the [WorldPacket]
function WorldPacket:WriteLong(value) end

---
--- Writes an unsigned 32-bit integer value to the [WorldPacket].
---
---@param value uint32 @ : the uint32 value to be written to the [WorldPacket]
function WorldPacket:WriteULong(value) end

---
--- Writes a 32-bit floating-point value to the [WorldPacket].
---
---@param value float @ : the float value to be written to the [WorldPacket]
function WorldPacket:WriteFloat(value) end

---
--- Writes a 64-bit floating-point value to the [WorldPacket].
---
---@param value double @ : the double value to be written to the [WorldPacket]
function WorldPacket:WriteDouble(value) end

return WorldPacket

